-- CREATE TABLE RED
CREATE TABLE redes (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    imagen VARCHAR(150) NOT NULL,
    alt_img VARCHAR(200) NOT NULL,
    nombre VARCHAR (80) NOT NULL,
    enlace VARCHAR (200) NOT NULL,
    done BOOLEAN NOT NULL DEFAULT 0,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);